version: "3"

services:
  database:
    image: postgres:latest
    network_mode: "host"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: hjkhjk
        POSTGRES_DB: clientx_org_sdf0sdf_dev
        SCHEMA: public
        APPUSER: app_user
    volumes:
      - ./db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./db/pgdata:/var/lib/postgresql/data
    restart: always

  webserver:
    build: 
      context: ./webserver
    image: webserver
    network_mode: "host"
    # mount point for application in tomcat
    volumes:
      - ./serviceapp/target/ServiceApp:/usr/local/tomcat/webapps/ServiceApp
    restart: always
    
  frontend:
    build: 
      context: ./serviceapp-frontend
    image: serviceapp-frontend
    network_mode: "host"
    volumes:    
      - ./serviceapp-frontend/src:/app/src
    restart: always